import { pgTable, text, timestamp, jsonb, pgEnum, index } from "drizzle-orm/pg-core";
import { createId } from "@paralleldrive/cuid2";
import { user } from "./auth";

export const auditKindEnum = pgEnum("audit_kind", [
  "bom.created",
  "bom.line.added",
  "bom.line.moved",
  "bom.line.qty.updated",
  "bom.line.removed",
  "bom.export.generated",
  "bom.section.created",
  "bom.section.renamed",
  "bom.section.reordered",
  "bom.section.deleted",
  "approval.requested",
  "approval.approved",
  "approval.rejected",
  "vendor.created",
  "item.created",
  "catalog.imported",
  "catalog.exported",
  "vendors.exported",
  "bom.revision.committed",
  "bom.revision.branched",
  "bom.revision.discarded",
  "user.created",
  "user.disabled",
  "project.deleted",
  "project.restored",
  "bom.renamed",
  "bom.deleted",
  "bom.duplicated",
  "procurement.email.sent",
  "drawing.created",
  "drawing.updated",
  "drawing.deleted",
  "drawing.revision.created",
  "drawing.status.changed",
  "drawing.comment.added",
  "drawing.notification.sent",
  "drawing.notification.failed",
  "drawing.settings.updated",
  "drawing.time.logged",
  "drawing.time.deleted",
  "drawing.remark.added",
  "drawing.remark.resolved",
  "drawing.remark.reopened",
  "drawing.transmittal.sent",
  "drawing.transmittal.acknowledged",
  "drawing.reminders.sent",
  "drawing.reminders.failed",
  "drawing.report.exported",
  "bom.drawing.linked",
  "bom.drawing.unlinked",
  "bom.drawing.updated",
  "project.updated",
  "project.contact.changed",
  "project.milestone.changed",
  "project.disciplines.changed",
  "dashboard.report.exported",
  "auth.signin",
  "auth.signin.failed",
  "user.password.changed",
  "user.password.reset",
  "user.password.reset.requested",
  "user.role.changed",
  "vendor.updated",
  "vendor.deleted",
  "item.updated",
  "item.deleted",
  "approval.cancelled",
  "settings.procurement.updated",
  "drawing.revision.bom_impact",
  "bom.drawing.checked",
  "drawing.file.uploaded",
  "drawing.file.removed",
  "drawing.file.downloaded",
  "bom.imported",
]);

export const auditLog = pgTable(
  "audit_log",
  {
    id: text("id").primaryKey().$defaultFn(() => createId()),
    actorId: text("actor_id").references(() => user.id, { onDelete: "set null" }),
    kind: auditKindEnum("kind").notNull(),
    refType: text("ref_type"),
    refId: text("ref_id"),
    summary: text("summary").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  t => ({
    createdIdx: index("audit_created_idx").on(t.createdAt),
    kindIdx: index("audit_kind_idx").on(t.kind, t.createdAt),
  }),
);
