import type { Line } from "@/components/builder/sectioned-line-table";
import type { SectionInfo } from "@/components/builder/section-row";

export function DocumentPreview({
  project, revisionLetter, lines, sections, referenceDrawings = [], generatedOn,
}: {
  project: { code: string; name: string; owner: string; target: string };
  revisionLetter: string;
  lines: Line[];
  sections: SectionInfo[];
  referenceDrawings?: string[];
  generatedOn: string;
}) {
  const uncat = lines.filter(l => l.sectionId === null);
  const sectionGroups = sections
    .slice()
    .sort((a, b) => a.position - b.position)
    .map(section => ({
      section,
      lines: lines.filter(l => l.sectionId === section.id),
    }));

  const COLS = 6;

  return (
    <div className="doc-preview">
      <div className="doc-head">
        <div>
          <h2 className="doc-title">Bill of Materials</h2>
          <div className="doc-meta" style={{ marginTop: 4 }}>
            {project.code} — {project.name} · Rev. {revisionLetter} · {generatedOn}
          </div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div style={{ fontWeight: 600, fontSize: 13 }}>Insta Engineering Team</div>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 24, marginBottom: 18, fontSize: 11.5 }}>
        <Meta label="Project owner" value={project.owner} />
        <Meta label="Target build" value={project.target} />
        {referenceDrawings.length > 0 && (
          <div style={{ gridColumn: "1 / -1" }}>
            <Meta label="Reference drawings" value={referenceDrawings.join(" · ")} />
          </div>
        )}
      </div>

      <div className="doc-table-wrap">
        <table className="doc-table max-[701px]:min-w-[620px]">
          <thead>
            <tr>
              <th>SKU</th>
              <th>Description</th>
              <th>Unit</th>
              <th className="num">Qty</th>
              <th>Manufacturer</th>
              <th>Vendor</th>
            </tr>
          </thead>
          <tbody>
            {uncat.length > 0 && (
              <SectionGroup title="Uncategorized" titleStyle="muted" lines={uncat} cols={COLS} />
            )}
            {sectionGroups.map(({ section, lines: groupLines }) => (
              <SectionGroup key={section.id} title={section.name} titleStyle="bold" lines={groupLines} cols={COLS} />
            ))}
          </tbody>
        </table>
      </div>

      <div style={{ marginTop: 32, paddingTop: 14, borderTop: "1px solid var(--line-soft)", fontSize: 10.5, color: "var(--text-3)", display: "flex", flexWrap: "wrap", gap: "4px 12px", justifyContent: "space-between" }}>
        <span>Generated by BOM Studio · Insta</span>
        <span>Page 1 of 1</span>
      </div>
    </div>
  );
}

function SectionGroup({
  title, titleStyle, lines, cols,
}: {
  title: string;
  titleStyle: "bold" | "muted";
  lines: Line[];
  cols: number;
}) {
  if (lines.length === 0) return null;
  return (
    <>
      <tr>
        <td
          colSpan={cols}
          style={{ background: "var(--surface-2)", fontSize: 11.5, ...(titleStyle === "bold" ? { fontWeight: 700, letterSpacing: "-0.01em" } : { fontStyle: "italic", color: "var(--text-3)" }) }}
        >
          {title}
        </td>
      </tr>
      {lines.map((l) => (
        <tr key={l.id}>
          <td className="mono">{l.sku}</td>
          <td>{l.description}</td>
          <td>{l.unit}</td>
          <td className="num">{l.qty}</td>
          <td>{l.manufacturer || "—"}</td>
          <td>{l.vendorName ?? "—"}</td>
        </tr>
      ))}
    </>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="muted" style={{ textTransform: "uppercase", fontSize: 10, letterSpacing: ".06em", marginBottom: 3 }}>{label}</div>
      <div style={{ fontWeight: 500, overflowWrap: "anywhere" }}>{value}</div>
    </div>
  );
}
