import type { Line } from "@/components/builder/bom-line-table";

export function DocumentPreview({
  project, revisionLetter, lines, generatedOn,
}: {
  project: { code: string; name: string; owner: string; target: string; quantity: number };
  revisionLetter: string;
  lines: Line[];
  generatedOn: string;
}) {
  const subtotal = lines.reduce((s, l) => s + l.qty * Number(l.unitPriceSnapshot), 0);
  const tax = subtotal * 0.08;
  const grand = subtotal + tax;

  return (
    <div className="rounded-lg border border-[var(--color-line)] bg-[var(--color-surface)] px-11 py-9 shadow-[var(--shadow-elev)]">
      <div className="mb-5 flex items-start justify-between border-b-2 border-[var(--color-text)] pb-4">
        <div>
          <h2 className="m-0 text-[24px] font-bold tracking-tight">Bill of Materials</h2>
          <div className="mt-1 text-[12px] text-[var(--color-text-3)]">
            {project.code} — {project.name} · Rev. {revisionLetter} · {generatedOn}
          </div>
        </div>
        <div className="text-right">
          <div className="text-[13px] font-semibold">Halcyon Robotics</div>
          <div className="text-[12px] text-[var(--color-text-3)]">438 Industrial Way · Oakland, CA</div>
          <div className="text-[12px] text-[var(--color-text-3)]">procurement@halcyon-robotics.com</div>
        </div>
      </div>

      <div className="mb-5 grid grid-cols-3 gap-6 text-[11.5px]">
        <Meta label="Project owner" value={project.owner} />
        <Meta label="Target build" value={project.target} />
        <Meta label="Quantity" value={`${project.quantity} units`} />
      </div>

      <table className="w-full border-collapse text-[11.5px]">
        <thead>
          <tr className="bg-[var(--color-surface-3)] text-[10.5px] uppercase tracking-wider">
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-left font-semibold">#</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-left font-semibold">SKU</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-left font-semibold">Description</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-left font-semibold">Vendor</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-left font-semibold">Unit</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-right font-semibold">Qty</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-right font-semibold">Unit price</th>
            <th className="border-b border-[var(--color-line)] px-2 py-1.5 text-right font-semibold">Total</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((l, i) => (
            <tr key={l.id}>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5 text-[var(--color-text-3)]">{i + 1}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5 font-mono">{l.sku}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5">{l.description}<div className="text-[10px] text-[var(--color-text-3)]">{l.manufacturer}</div></td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5">{l.vendorName ?? "—"}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5">{l.unit}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5 text-right tabular-nums">{l.qty}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5 text-right tabular-nums">${Number(l.unitPriceSnapshot).toFixed(3)}</td>
              <td className="border-b border-[var(--color-line)] px-2 py-1.5 text-right font-medium tabular-nums">${(l.qty * Number(l.unitPriceSnapshot)).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="ml-auto mt-5 w-72 text-[12px]">
        <div className="flex justify-between py-1"><span>Subtotal</span><span className="tabular-nums">${subtotal.toFixed(2)}</span></div>
        <div className="flex justify-between py-1"><span>Estimated tax (8%)</span><span className="tabular-nums">${tax.toFixed(2)}</span></div>
        <div className="mt-1.5 flex justify-between border-t-2 border-[var(--color-text)] pt-2 text-[14px] font-bold">
          <span>Grand total</span><span className="tabular-nums">${grand.toFixed(2)}</span>
        </div>
      </div>

      <div className="mt-8 flex justify-between border-t border-[var(--color-line-soft)] pt-3.5 text-[10.5px] text-[var(--color-text-3)]">
        <span>Generated by BOM Studio · Halcyon Robotics</span>
        <span>Page 1 of 1</span>
      </div>
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="mb-0.5 text-[10px] uppercase tracking-wider text-[var(--color-text-3)]">{label}</div>
      <div className="font-medium">{value}</div>
    </div>
  );
}
