// Preview & Generate page
function Preview({ project, bomList, columns, onBack, onGenerate }) {
  const I = window.Icon;
  const itemBySku = useMemo(() => Object.fromEntries(window.ITEMS.map(i => [i.sku, i])), []);
  const rows = bomList.map(b => ({ ...itemBySku[b.sku], qty: b.qty }));
  const subtotal = rows.reduce((s, r) => s + r.qty * r.price, 0);
  const tax = subtotal * 0.08;
  const grand = subtotal + tax;

  return (
    <>
      <div className="page-head">
        <div>
          <h1 className="page-title">Preview & Generate</h1>
          <p className="page-sub">Review the generated document, then export to Excel for procurement.</p>
        </div>
        <div className="split">
          <div className="steps">
            <div className="step done"><span className="num"><I.Check/></span> Build</div>
            <span className="arrow">›</span>
            <div className="step active"><span className="num">2</span> Preview</div>
            <span className="arrow">›</span>
            <div className="step"><span className="num">3</span> Generate</div>
          </div>
          <button className="btn" onClick={onBack}><I.ArrowLeft/> Back to builder</button>
          <button className="btn"><I.Print/> Print</button>
          <button className="btn btn-primary" onClick={onGenerate}><I.Download/> Generate Excel</button>
        </div>
      </div>

      <div style={{display:"grid", gridTemplateColumns:"1fr 280px", gap:16, alignItems:"start"}}>
        <div className="doc-preview">
          <div className="doc-head">
            <div>
              <h2 className="doc-title">Bill of Materials</h2>
              <div className="doc-meta" style={{marginTop:4}}>
                {project ? `${project.code} — ${project.name}` : "DRAFT-2412 — New BOM"} · Rev. A · Apr 29, 2026
              </div>
            </div>
            <div style={{textAlign:"right"}}>
              <div style={{fontWeight:600, fontSize:13}}>Halcyon Robotics</div>
              <div className="doc-meta">438 Industrial Way · Oakland, CA</div>
              <div className="doc-meta">procurement@halcyon-robotics.com</div>
            </div>
          </div>

          <div style={{display:"grid", gridTemplateColumns:"1fr 1fr 1fr", gap:24, marginBottom:18, fontSize:11.5}}>
            <div>
              <div className="muted" style={{textTransform:"uppercase", fontSize:10, letterSpacing:".06em", marginBottom:3}}>Project owner</div>
              <div style={{fontWeight:500}}>{project?.owner || "M. Chen"}</div>
            </div>
            <div>
              <div className="muted" style={{textTransform:"uppercase", fontSize:10, letterSpacing:".06em", marginBottom:3}}>Target build</div>
              <div style={{fontWeight:500}}>{project?.target || "May 14, 2026"}</div>
            </div>
            <div>
              <div className="muted" style={{textTransform:"uppercase", fontSize:10, letterSpacing:".06em", marginBottom:3}}>Quantity</div>
              <div style={{fontWeight:500}}>50 units</div>
            </div>
          </div>

          <table className="doc-table">
            <thead><tr>
              <th style={{width:32}}>#</th>
              <th>SKU</th>
              <th>Description</th>
              <th>Vendor</th>
              <th>Unit</th>
              <th className="num">Qty</th>
              <th className="num">Unit price</th>
              <th className="num">Total</th>
            </tr></thead>
            <tbody>
              {rows.map((r, i) => (
                <tr key={r.sku}>
                  <td className="muted">{i+1}</td>
                  <td className="mono">{r.sku}</td>
                  <td>{r.desc}<div style={{fontSize:10, color:"var(--text-3)"}}>{r.mfr}</div></td>
                  <td>{r.vendor}</td>
                  <td>{r.unit}</td>
                  <td className="num">{r.qty}</td>
                  <td className="num">${r.price.toFixed(3)}</td>
                  <td className="num" style={{fontWeight:500}}>${(r.qty*r.price).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="doc-totals">
            <div className="row"><span>Subtotal</span><span className="tabular">${subtotal.toFixed(2)}</span></div>
            <div className="row"><span>Estimated tax (8%)</span><span className="tabular">${tax.toFixed(2)}</span></div>
            <div className="row grand"><span>Grand total</span><span className="tabular">${grand.toFixed(2)}</span></div>
          </div>

          <div style={{marginTop:32, paddingTop:14, borderTop:"1px solid var(--line-soft)", fontSize:10.5, color:"var(--text-3)", display:"flex", justifyContent:"space-between"}}>
            <span>Generated by BOM Studio · Halcyon Robotics</span>
            <span>Page 1 of 1</span>
          </div>
        </div>

        <div style={{display:"flex", flexDirection:"column", gap:12, position:"sticky", top:68}}>
          <div className="card">
            <div className="card-head"><h3 className="card-title">Summary</h3></div>
            <div style={{padding:"12px 16px"}}>
              <dl className="kv">
                <dt>Lines</dt><dd>{rows.length}</dd>
                <dt>Total units</dt><dd>{rows.reduce((s,r)=>s+r.qty,0).toLocaleString()}</dd>
                <dt>Vendors</dt><dd>{new Set(rows.map(r=>r.vendor)).size}</dd>
                <dt>Subtotal</dt><dd>${subtotal.toFixed(2)}</dd>
                <dt>Tax</dt><dd>${tax.toFixed(2)}</dd>
                <dt style={{fontWeight:600, color:"var(--text)"}}>Grand total</dt><dd style={{fontWeight:600}}>${grand.toFixed(2)}</dd>
              </dl>
            </div>
          </div>

          <div className="card">
            <div className="card-head"><h3 className="card-title">Export options</h3></div>
            <div style={{padding:"12px 16px", display:"flex", flexDirection:"column", gap:10}}>
              <label style={{display:"flex", alignItems:"center", gap:8, fontSize:12.5}}>
                <input type="checkbox" defaultChecked/> Include vendor pricing
              </label>
              <label style={{display:"flex", alignItems:"center", gap:8, fontSize:12.5}}>
                <input type="checkbox" defaultChecked/> Include stock availability
              </label>
              <label style={{display:"flex", alignItems:"center", gap:8, fontSize:12.5}}>
                <input type="checkbox"/> Group by vendor (separate sheets)
              </label>
              <label style={{display:"flex", alignItems:"center", gap:8, fontSize:12.5}}>
                <input type="checkbox"/> Include cover page
              </label>
              <hr className="div"/>
              <div className="field-label">Format</div>
              <select className="select"><option>Excel (.xlsx)</option><option>CSV</option><option>PDF</option></select>
            </div>
          </div>

          <div className="card">
            <div className="card-head"><h3 className="card-title">Approvers</h3></div>
            <div style={{padding:"4px 0"}}>
              {[
                ["MC","Marcus Chen","Engineering","done"],
                ["SP","Sarah Patel","Procurement","active"],
                ["RH","Ravi Hassan","Finance","pending"],
              ].map(([i,n,r,s]) => (
                <div key={n} style={{display:"flex", alignItems:"center", gap:10, padding:"8px 16px", fontSize:12.5}}>
                  <div className="avatar" style={{width:24, height:24, fontSize:10}}>{i}</div>
                  <div style={{flex:1}}>
                    <div>{n}</div>
                    <div className="muted" style={{fontSize:11}}>{r}</div>
                  </div>
                  {s==="done" && <span className="badge b-green"><I.Check/> Signed</span>}
                  {s==="active" && <span className="badge b-amber"><span className="dot"/>Reviewing</span>}
                  {s==="pending" && <span className="badge b-gray"><span className="dot"/>Pending</span>}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
window.Preview = Preview;
